### ISSUE TITLE
MQTT

### ISSUE THREAD

**Issue by PhHJames** [kongyuebin1/dongfeng-pay#4]
请问需要自己搭建MQTT吗，我自己搭建了一个 用MQTT.fx客户端工具可以连上，代码里就是连不上，err 链接active mq 失败： EOF。请问MQTT服务端要作何特别配置吗。

**Comment by PhHJames** [comment]
不好意思。我搞错了 是active mq

**Comment by zkbqhuang** [comment]
链接active mq 失败： dial tcp 139.196.82.110:61613: connectex: No connection could be made because the target machine actively refused it.

你说的是这个问题吗？  你解决了吗？
