### ISSUE TITLE
关于Model层的错误处理

### ISSUE THREAD

**Issue by YahuiAn** [kongyuebin1/dongfeng-pay#5]
https://github.com/kongyuebin1/dongfeng-pay/blob/6f5d77a78007ebb0d1c9eac90eaf670e7035b11c/service/models/account.go#L35
我看到Model层发生错误后，只是打日志，并没有将错误传递给调用者。感觉返回error要比bool好一些，而且error携带的信息要多一点。
```go
func InsetAcount(account AccountInfo) error {
	o := orm.NewOrm()
	_, err := o.Insert(&account)
	if err != nil {
		return error
	}
	return nil
}
```
至于调用者拿到error后，是记录日志，还是机器人告警，可以自由处理。
我是小白，仅仅提一下自己的看法^_^

**Comment by kongyuebin1** [comment]
model层的错误已经打印出来，service只需要知道model已经执行的结果，然后自行处理接下来的逻辑
